source-application: add recording support when streaming quality drops
hwangsaeul/gaeul pull request #59
Opened 2020-12-01 19:04 UTC by raghaven447

The logic to start/stop the recording on streaming quality drop/regain has been added into the agent (Gaeul).

2020-12-04 11:45 UTC, raghaven447 commented
I believe that the support to set the adaptor type on the GaeguliPipeline according to user choice should be added here in order to enable/disable the recording when streaming quality dropd/regains. Please comment.

2020-12-08 12:45 UTC, justinjoy requested changes

2020-12-08 12:45 UTC, justinjoy commented on gaeul/source/source-application.c
> +  gchar *record_location;
This pointer should be freed in `gaeguli_nest_unref()`.

2020-12-08 12:45 UTC, justinjoy commented on gaeul/source/source-application.c
> +  g_debug ("target removed");
`error->message` may have valuable information for debuggers.

2020-12-08 12:45 UTC, justinjoy commented on gaeul/source/source-application.c
> +  gaeguli_target_start (nest->record_stream, &error);
Can we reuse `error` without explicit free?

2020-12-08 12:45 UTC, justinjoy commented on gaeul/source/source-application.c
> +      nest->record_location, &error);
Please add error handling. `gaeguli_pipeline_add_recording_target()` can return NULL.

2020-12-08 12:45 UTC, justinjoy commented on gaeul/source/source-application.c
> +  GaeguliTarget *record_stream;
This should be freed when stopping.

2020-12-08 12:45 UTC, justinjoy commented on gaeul/source/source-application.c
> +  GaeguliStreamAdaptor *adaptor;
This should be freed in `gaeguli_nest_unref()`.

2020-12-08 12:45 UTC, justinjoy commented on gaeul/source/source-application.c
> +  nest->adaptor = gaeguli_target_get_stream_adaptor (nest->target_stream);
I am not sure whether the pipeline emits stream-start only once.
We should avoid memory leakage.

2020-12-08 12:53 UTC, justinjoy commented
> I believe that the support to set the adaptor type on the GaeguliPipeline according to user choice should be added here in order to enable/disable the recording when streaming quality dropd/regains. Please comment.

Yes, the recording feature can be enabled/disabled by user, but since we have only a bandwidth adaptor,  I don't think we need to provide an option to choose a different adaptor now.

2020-12-09 04:52 UTC, justinjoy approved these changes
LGTM

2020-12-09 04:59 UTC, merged